### ISSUE TITLE
Версия 2.51 пара поправок к исходникам для предотвращения проблем

### ISSUE THREAD

**Issue by VictorVG** [yutsis/YMSPlugins#2]
первая мелкая, при сборке в IDE вылезает  в файле ./YMSPlugin.h строка 10: 

`#include <plugin.hpp> // exact path for FAR1/2/3 is defined in project, property manager or environment`

сообщением об ошибке что plugin.hpp не найден - компиллер ищет его в SDK, а его там нет. :) Поправил просто:

`#include  "plugin.hpp" // exact path for FAR1/2/3 is defined in project, property manager or environment`

и пусть локальную копию файла читает который я у себя кладу рядом с ним, но это из мелких неудобств сборки - главное не забыть про них. :)

а вот вторая коварнее будет - в файле ./XMLDOM/XMLDOM.cpp в строке 25 есть фрагмент кода:

`info->MinFarVersion = MAKEFARVERSION(3,0,0,2927,VS_RELEASE);`

статически задающий минимальную версию Far необходимую для запуска плагина. Если мы его собираем с хидерами от b2927 потенциальной проблемы конфликта "_Plugin API в Far - Plugin API в XMLDOM_" не возникает до момента пока мы не встретимся со случаем "Plugin API Far не совпадает с Plugin API с которым собран XPLDOM" - тут нас могут ждать любые сюрпризы, а зачем они нам? Потому поправил этот фрагмент кода  в ./XMLDOM/XMLDOM.cpp так:

после строки 8 `#include "..\PluginSettings.hpp"` добавил строку:

`#include "..\plugin.hpp" /* added new string */`

и изменил строку 25

`info->MinFarVersion = MAKEFARVERSION(3,0,0,2927,VS_RELEASE);`

на

 `info->MinFarVersion = MAKEFARVERSION(3,0,0,FARMANAGERVERSION_BUILD,VS_RELEASE);`

где _FARMANAGERVERSION_BUILD_ читается из ../plugin.hpp что предотвратило ошибочное сообщение в GetGlobalInfoW() неверного номера билда Plugin API для которого собрана данная копия плагина.

Вот собранный с внесёнными исправлениями XMLDOM v2.51.0.4400 [**XMLDOM_v2.51_x86_AMD64_b4400.zip**](https://github.com/yutsis/YMSPlugins/files/129742/XMLDOM_v2.51_x86_AMD64_b4400.zip) и его исходники [**YMSPlugins-src.zip**](https://github.com/yutsis/YMSPlugins/files/129743/YMSPlugins-src.zip).

**P.S.**

Возможно я излишне перестраховался, но по моему лучше предотвратить возможные проблемы в зародыше.

**P.P.S.**

перепроверил на сборке с ПлагРинга v2.51.0.0 для  Far v3.0.4455 - запускается и читает тестовый XML даже под b3702, хотя по идее формально должна бы ему сказать через GetGlobalInfoW() что ей нужен b4455, но она-то передаёт ему что ей нужен b2927 и мы балансируем на грани фола...

**Comment by yutsis** [comment]
Проблема с plugin.hpp решается не так. Когда определены переменные окружения FAR1, FAR2 и т.д., компилятор должен находить plugin.hpp через них, там же в проекте везде добавляются фаровские каталоги инклудов из стандартной установки фара.
Про MinFarVersion отвечу чуть позже.

**Comment by yutsis** [comment]
Про MinFarVersion: а почему, собственно, я должен требовать версию фара не старее, чем стоит у меня? Я сдвигаю это число только в том случае, если знаю о несовместимости API.

**Comment by VictorVG** [comment]
Согласен, если работает, то и смысла ставить более высокую нет. Просто страховка на случай смены Plugin SDK.

А с plugin.hpp тут просто - у меня на машине стоит с десяток разных тест- и сборочных комплектов, и потому если я определю для них %FARHOME% и к примеру %FARDEV%\COMMON сбои сборки гарантированы. Именно потому мне проще указать относительный путь и туда кинуть нужные файлы.
